name: Run Script on AWS EC2

on:
  push:
    branches:
      - main

jobs:
  run-script-on-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Create identifier file
      env:
        ACTIONS_RUNNER_DEBUG: false
      run: echo "${{ secrets.EC2_SSH_KEY }}" > japanese_text_analyser.pem

    - name: Set file permissions
      run: chmod 600 japanese_text_analyser.pem

    - name: Connect to server and restart website
      run: |
        ssh -o StrictHostKeyChecking=no -i japanese_text_analyser.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE }} '
        cd japanese_text_analyser && 
        source japanese_text_analyser_env/bin/activate && 
        chmod +x ./deploy.sh && yes | ./deploy.sh'
